/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'message' : string,
  'response' : string,
}
export interface DataAnalysisInsight {
  'id' : bigint,
  'insights' : string,
  'inputData' : string,
}
export interface DecisionToolRecommendation {
  'id' : bigint,
  'answers' : Array<string>,
  'steps' : Array<string>,
  'recommendation' : string,
}
export interface PersonalityQuizResult {
  'id' : bigint,
  'report' : string,
  'answers' : Array<bigint>,
  'personalityType' : string,
}
export interface _SERVICE {
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getDataInsights' : ActorMethod<[], Array<DataAnalysisInsight>>,
  'getPersonalityResults' : ActorMethod<[], Array<PersonalityQuizResult>>,
  'getRecommendations' : ActorMethod<[], Array<DecisionToolRecommendation>>,
  'saveChatMessage' : ActorMethod<[string, string], bigint>,
  'saveDataInsight' : ActorMethod<[string, string], bigint>,
  'saveQuizResult' : ActorMethod<[Array<bigint>, string, string], bigint>,
  'saveRecommendation' : ActorMethod<
    [Array<string>, Array<string>, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];