/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
  'response' : IDL.Text,
});
export const DataAnalysisInsight = IDL.Record({
  'id' : IDL.Nat,
  'insights' : IDL.Text,
  'inputData' : IDL.Text,
});
export const PersonalityQuizResult = IDL.Record({
  'id' : IDL.Nat,
  'report' : IDL.Text,
  'answers' : IDL.Vec(IDL.Nat),
  'personalityType' : IDL.Text,
});
export const DecisionToolRecommendation = IDL.Record({
  'id' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Text),
  'steps' : IDL.Vec(IDL.Text),
  'recommendation' : IDL.Text,
});

export const idlService = IDL.Service({
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getDataInsights' : IDL.Func([], [IDL.Vec(DataAnalysisInsight)], ['query']),
  'getPersonalityResults' : IDL.Func(
      [],
      [IDL.Vec(PersonalityQuizResult)],
      ['query'],
    ),
  'getRecommendations' : IDL.Func(
      [],
      [IDL.Vec(DecisionToolRecommendation)],
      ['query'],
    ),
  'saveChatMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'saveDataInsight' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'saveQuizResult' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveRecommendation' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'message' : IDL.Text,
    'response' : IDL.Text,
  });
  const DataAnalysisInsight = IDL.Record({
    'id' : IDL.Nat,
    'insights' : IDL.Text,
    'inputData' : IDL.Text,
  });
  const PersonalityQuizResult = IDL.Record({
    'id' : IDL.Nat,
    'report' : IDL.Text,
    'answers' : IDL.Vec(IDL.Nat),
    'personalityType' : IDL.Text,
  });
  const DecisionToolRecommendation = IDL.Record({
    'id' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Text),
    'steps' : IDL.Vec(IDL.Text),
    'recommendation' : IDL.Text,
  });
  
  return IDL.Service({
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getDataInsights' : IDL.Func([], [IDL.Vec(DataAnalysisInsight)], ['query']),
    'getPersonalityResults' : IDL.Func(
        [],
        [IDL.Vec(PersonalityQuizResult)],
        ['query'],
      ),
    'getRecommendations' : IDL.Func(
        [],
        [IDL.Vec(DecisionToolRecommendation)],
        ['query'],
      ),
    'saveChatMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'saveDataInsight' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'saveQuizResult' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveRecommendation' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };